@extends('layout.template')

@section('content')
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>NIM</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Aheng</td>
                <td>517388</td>
                <td>B</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Agus</td>
                <td>517639</td>
                <td>A</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Mia</td>
                <td>73884</td>
                <td>A</td>
            </tr>
        </tbody>
    </table>
@endsection
